version: '3.8'

services:
  letter-frontend:
    image: severinsch/letter-frontend:latest
    restart: unless-stopped
    networks:
      - proxy-tier

  letter-backend:
    image: severinsch/letter-api:latest
    restart: unless-stopped
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true
